---
name: call on ancient blood
traits: []
count: reaction
trigger: You attempt a saving throw against a magical effect, but you haven't rolled
  yet
description: Your ancestors' innate resistance to magic surges before slowly ebbing
  down. You gain a +1 circumstance bonus to saving throws on the triggering save and
  other saves against magical effects until the end of this turn.
