---
count: free_action
description: "You apply one of the following debilitations, which lasts until the
  end of your next turn:\n\t•\tDebilitation The target takes a -10-foot status penalty
  to its Speeds.\n\t•\tDebilitation The target becomes Enfeebled 1.\nEffect: Debilitating
  Strike"
name: debilitating strike
source:
  book: Pathfinder Player Core
  publisher: paizo
traits:
- rogue
trigger: Your Strike hits an off-guard creature and deals damage
